cc_library(
    name = "functions",
    hdrs = ["functions.h"],
)

cc_library(
    name = "newtons_method",
    srcs = ["newtons_method.cpp"],
    hdrs = ["newtons_method.h"],
    visibility = ["//visibility:public"],
    deps = ["//root_finders:functions"],
)
