cc_test(
    name = "jacobi_solver_tests",
    srcs = ["jacobi_solver_tests.cpp"],
    deps = [
        "//matrix_solvers/iterative_solvers:gauss_seidel_method",
        "//matrix_solvers/iterative_solvers:jacobi_method",
        "@com_google_googletest//:gtest_main",
    ],
)
