cc_test(
    name = "direct_solver_tests",
    srcs = ["direct_solver_tests.cpp"],
    deps = [
        "//matrix_solvers/direct_solvers:backwards_substitution",
        "//matrix_solvers/direct_solvers:doolittle",
        "@com_google_googletest//:gtest_main",
    ],
)
