# This is a basic workflow to help you get started with Actions

name: Heimdall

# Controls when the workflow will run

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  pull_request:
    types: [opened, synchronize, labeled]
  issue_comment:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a multiple jobs
  bazel-build-and-test-clang-macos-x86_64:
    if: contains(github.event.pull_request.labels.*.name, 'check') || contains(github.event.comment.body, 'recheck')

    # The type of runner that the job will run on
    runs-on: macos-13

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout to PR branch
        uses: actions/checkout@v4

      - name: Setup bazel
        uses: bazelbuild/setup-bazelisk@v3

      - name: echo gcc version
        run: gcc --version

      - name: debug build
        run: bazel build --config=gcc14_osx_x86_64 --toolchain_resolution_debug=".*" --config=debug --verbose_failures --subcommands //root_finders/...

      - name: fastbuild
        run: bazel test --config=gcc14_osx_x86_64 --toolchain_resolution_debug=".*" --compilation_mode=fastbuild --cache_test_results=no --test_output=all --verbose_failures --subcommands //root_finders/...

  bazel-build-and-test-clang-macos-arm64:
    if: contains(github.event.pull_request.labels.*.name, 'check') || contains(github.event.comment.body, 'recheck')

    # The type of runner that the job will run on
    runs-on: macos-14

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout to PR branch
        uses: actions/checkout@v4

      - name: Setup bazel
        uses: bazelbuild/setup-bazelisk@v3
        
      - name: debug build root_finders
        run: bazel build --config=osx_clang15_aarch64 --toolchain_resolution_debug=".*" --config=debug --verbose_failures --subcommands //root_finders/...

      - name: fastbuild
        run: bazel build --config=osx_clang15_aarch64 --toolchain_resolution_debug=".*" --verbose_failures --subcommands //root_finders/...

      - name: test
        run: bazel test --config=osx_clang15_aarch64 --toolchain_resolution_debug=".*" --compilation_mode=fastbuild --cache_test_results=no --test_output=all --verbose_failures --subcommands //root_finders/...
