name: Issue-CI

on: issue_comment

jobs:
  bazel-build-on-issue:
    # This job only runs for pull request comments
    name: Build from PR comment
    # if: ${{ github.event.issue.pull_request }}
    if: contains(github.event.issue.labels.*.name, 'check')
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v1
      - run: bazel build --copt="-std=c++14" //...
